# Generated by Django 5.1.2 on 2026-03-23 18:07

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplyTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("store", "Store"), ("hub", "Hub")], max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("reserved", "Reserved"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("received", "Received"),
                            ("rejected", "Rejected"),
                            ("canceled", "Canceled"),
                        ],
                        default="requested",
                        max_length=24,
                    ),
                ),
                (
                    "transfer_scope",
                    models.CharField(
                        choices=[
                            ("same_region_store", "Same-Region Store"),
                            ("hub_to_store", "Hub To Store"),
                            ("cross_region_hub", "Cross-Region Hub"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "distance_miles",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("is_ai_draft", models.BooleanField(default=False)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-requested_at",),
            },
        ),
        migrations.CreateModel(
            name="SupplyTransferLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity_requested",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "quantity_approved",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
            ],
            options={
                "ordering": ("inventory_item__sku",),
            },
        ),
        migrations.CreateModel(
            name="SupplyHub",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hub_code", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=140)),
                ("city", models.CharField(max_length=80)),
                ("state_code", models.CharField(max_length=2)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_hubs",
                        to="stores.region",
                    ),
                ),
            ],
            options={
                "ordering": ("region__code", "hub_code"),
            },
        ),
        migrations.CreateModel(
            name="HubInventoryBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "on_hand_quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_balances",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_balances",
                        to="supply_hubs.supplyhub",
                    ),
                ),
            ],
            options={
                "ordering": ("hub__hub_code", "inventory_item__sku"),
            },
        ),
    ]
