# Generated by Django 5.1.2 on 2026-03-23 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("stores", "0001_initial"),
        ("supply_hubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supplytransfer",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplytransfer",
            name="destination_store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inbound_transfers",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="supplytransfer",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplytransfer",
            name="source_hub",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_transfers",
                to="supply_hubs.supplyhub",
            ),
        ),
        migrations.AddField(
            model_name="supplytransfer",
            name="source_store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_transfers",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="supplytransferlineitem",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfer_line_items",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="supplytransferlineitem",
            name="transfer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="supply_hubs.supplytransfer",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubinventorybalance",
            constraint=models.UniqueConstraint(
                fields=("hub", "inventory_item"), name="unique_hub_inventory_balance"
            ),
        ),
        migrations.AddConstraint(
            model_name="hubinventorybalance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("on_hand_quantity__gte", 0), ("reserved_quantity__gte", 0)
                ),
                name="hub_inventory_quantities_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubinventorybalance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("on_hand_quantity__gte", models.F("reserved_quantity"))
                ),
                name="hub_inventory_reserved_not_greater_than_on_hand",
            ),
        ),
        migrations.AddIndex(
            model_name="supplytransfer",
            index=models.Index(
                fields=["status", "requested_at"], name="supply_hubs_status_e78320_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplytransfer",
            index=models.Index(
                fields=["destination_store", "status"],
                name="supply_hubs_destina_29f8e8_idx",
            ),
        ),
    ]
