# Generated by Django 5.1.2 on 2026-03-25 20:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_token", models.CharField(max_length=255, unique=True)),
                ("device_label", models.CharField(blank=True, max_length=120)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("ios", "iOS"),
                            ("android", "Android"),
                        ],
                        default="web",
                        max_length=16,
                    ),
                ),
                (
                    "push_provider",
                    models.CharField(
                        choices=[("web_push", "Web Push"), ("fcm", "FCM")],
                        default="web_push",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-last_seen_at",),
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ("is_read", "-created_at")},
        ),
        migrations.AddField(
            model_name="notification",
            name="delivery_channel",
            field=models.CharField(
                choices=[("in_app", "In-App"), ("push", "Push"), ("email", "Email")],
                default="in_app",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("generic", "Generic"),
                    ("import_result", "Import Result"),
                    ("machine_alert", "Machine Alert"),
                    ("order_update", "Order Update"),
                    ("repair_assignment", "Repair Assignment"),
                    ("transfer_update", "Transfer Update"),
                ],
                default="generic",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="payload_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="notificatio_user_id_f2ad08_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "delivery_status"],
                name="notificatio_notific_13b5f6_idx",
            ),
        ),
        migrations.AddField(
            model_name="deviceregistration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="deviceregistration",
            index=models.Index(
                fields=["user", "is_active", "-last_seen_at"],
                name="notificatio_user_id_3d6102_idx",
            ),
        ),
    ]
