# Generated by Django 5.1.2 on 2026-03-25 20:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncProjectionState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "receiver_scope_type",
                    models.CharField(
                        choices=[
                            ("region", "Region"),
                            ("store", "Store"),
                            ("global", "Global"),
                        ],
                        max_length=24,
                    ),
                ),
                ("receiver_scope_key", models.CharField(max_length=80)),
                ("receiver_label", models.CharField(max_length=160)),
                ("aggregate_type", models.CharField(max_length=80)),
                ("aggregate_id", models.CharField(max_length=80)),
                ("last_event_type", models.CharField(max_length=120)),
                ("last_entity_version", models.PositiveIntegerField(default=0)),
                ("source_scope", models.JSONField(blank=True, default=dict)),
                ("payload_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at",),
                "indexes": [
                    models.Index(
                        fields=["receiver_scope_type", "receiver_scope_key"],
                        name="sync_syncpr_receive_b2d97a_idx",
                    ),
                    models.Index(
                        fields=["aggregate_type", "aggregate_id"],
                        name="sync_syncpr_aggrega_058783_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "receiver_scope_type",
                            "receiver_scope_key",
                            "aggregate_type",
                            "aggregate_id",
                        ),
                        name="unique_sync_projection_receiver_entity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncConflictLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "receiver_scope_type",
                    models.CharField(
                        choices=[
                            ("region", "Region"),
                            ("store", "Store"),
                            ("global", "Global"),
                        ],
                        max_length=24,
                    ),
                ),
                ("receiver_scope_key", models.CharField(max_length=80)),
                ("receiver_label", models.CharField(max_length=160)),
                ("aggregate_type", models.CharField(max_length=80)),
                ("aggregate_id", models.CharField(max_length=80)),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("stale_event", "Stale Event"),
                            ("invalid_scope", "Invalid Scope"),
                            ("ownership_mismatch", "Ownership Mismatch"),
                            ("invalid_transition", "Invalid Transition"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outbox_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conflicts",
                        to="sync.syncoutboxevent",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["resolution_status", "conflict_type"],
                        name="sync_syncco_resolut_13fb04_idx",
                    ),
                    models.Index(
                        fields=["aggregate_type", "aggregate_id"],
                        name="sync_syncco_aggrega_c27b0f_idx",
                    ),
                ],
            },
        ),
    ]
