# Generated by Django 5.1.2 on 2026-04-04 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0003_syncprojectionstate_syncconflictlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncPeerDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("peer_node_id", models.CharField(max_length=80)),
                ("peer_url", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="syncoutboxevent",
            name="origin_node_id",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="syncoutboxevent",
            name="remote_event_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="syncoutboxevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origin_node_id__gt", "")),
                fields=("origin_node_id", "remote_event_id"),
                name="unique_peer_event_idempotency",
            ),
        ),
        migrations.AddField(
            model_name="syncpeerdelivery",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peer_deliveries",
                to="sync.syncoutboxevent",
            ),
        ),
        migrations.AddIndex(
            model_name="syncpeerdelivery",
            index=models.Index(
                fields=["status", "next_attempt_at"],
                name="sync_syncpe_status_100aa9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="syncpeerdelivery",
            unique_together={("event", "peer_node_id")},
        ),
    ]
