# Generated by Django 5.1.2 on 2026-03-23 18:07

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("imports", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("default_service_interval_days", models.PositiveIntegerField()),
                ("warning_max_operational_days", models.PositiveIntegerField()),
                ("error_max_days", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="RepairAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        default="scheduled",
                        max_length=24,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by_system", models.BooleanField(default=True)),
                ("route_batch_key", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("scheduled_for", "-priority_score"),
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("machine_uid", models.CharField(max_length=80, unique=True)),
                ("display_name", models.CharField(max_length=160)),
                ("operational_from_date", models.DateField()),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("repair-start", "Repair Start"),
                            ("repair-end", "Repair End"),
                            ("schedule-service", "Schedule Service"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("out-of-order", "Out of Order"),
                        ],
                        default="normal",
                        max_length=24,
                    ),
                ),
                ("current_status_date", models.DateField(blank=True, null=True)),
                ("last_service_date", models.DateField(blank=True, null=True)),
                ("next_service_due_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machines",
                        to="stores.store",
                    ),
                ),
                (
                    "machine_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="machines",
                        to="maintenance.machinetype",
                    ),
                ),
            ],
            options={
                "ordering": ("store__store_code", "machine_uid"),
            },
        ),
        migrations.CreateModel(
            name="MachineStatusEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("repair-start", "Repair Start"),
                            ("repair-end", "Repair End"),
                            ("schedule-service", "Schedule Service"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("out-of-order", "Out of Order"),
                        ],
                        max_length=24,
                    ),
                ),
                ("status_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="maintenance.machine",
                    ),
                ),
                (
                    "source_import_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_status_events",
                        to="imports.importjob",
                    ),
                ),
            ],
            options={
                "ordering": ("-status_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="MaintenancePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("max_days_between_service", models.PositiveIntegerField()),
                ("warning_shutdown_days", models.PositiveIntegerField()),
                ("schedule_service_window_days", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "machine_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="maintenance.machinetype",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_policies",
                        to="stores.region",
                    ),
                ),
            ],
            options={
                "ordering": ("machine_type__code", "region__code"),
            },
        ),
    ]
