# Generated by Django 5.1.2 on 2026-03-23 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maintenance", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="repairassignment",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repair_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="repairassignment",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repair_assignments",
                to="maintenance.machine",
            ),
        ),
        migrations.AddField(
            model_name="repairassignment",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repair_assignments",
                to="stores.store",
            ),
        ),
        migrations.AddIndex(
            model_name="machinestatusevent",
            index=models.Index(
                fields=["machine", "-status_date"],
                name="maintenance_machine_f508d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(
                fields=["store", "current_status"],
                name="maintenance_store_i_404bad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="repairassignment",
            index=models.Index(
                fields=["assigned_to", "status", "scheduled_for"],
                name="maintenance_assigne_120874_idx",
            ),
        ),
    ]
