# Generated by Django 5.1.2 on 2026-03-24 02:24

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_supplier_replenishments(apps, schema_editor):
    SupplierReplenishment = apps.get_model("inventory", "SupplierReplenishment")
    for replenishment in SupplierReplenishment.objects.all():
        update_fields = []
        if replenishment.quantity_requested == 0 and replenishment.quantity_received:
            replenishment.quantity_requested = replenishment.quantity_received
            update_fields.append("quantity_requested")
        if (
            replenishment.requested_by_id is None
            and replenishment.recorded_by_id is not None
        ):
            replenishment.requested_by_id = replenishment.recorded_by_id
            update_fields.append("requested_by")
        if replenishment.ordered_at is None and replenishment.received_at is not None:
            replenishment.ordered_at = replenishment.received_at
            update_fields.append("ordered_at")
        if replenishment.status != "received" and replenishment.received_at is not None:
            replenishment.status = "received"
            update_fields.append("status")
        if update_fields:
            replenishment.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplierreplenishment",
            options={"ordering": ("-ordered_at", "-received_at")},
        ),
        migrations.AddField(
            model_name="supplierreplenishment",
            name="expected_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierreplenishment",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplierreplenishment",
            name="ordered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierreplenishment",
            name="quantity_requested",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="supplierreplenishment",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_replenishments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplierreplenishment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordered", "Ordered"),
                    ("received", "Received"),
                    ("canceled", "Canceled"),
                ],
                default="received",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="supplierreplenishment",
            name="quantity_received",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="supplierreplenishment",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplierreplenishment",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recorded_replenishments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            backfill_supplier_replenishments, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="supplierreplenishment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_requested__gte", 0), ("quantity_received__gte", 0)
                ),
                name="supplier_replenishment_quantities_non_negative",
            ),
        ),
    ]
