# Generated by Django 5.1.2 on 2026-03-23 18:07

import uuid
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GuestOrderContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=160)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                ("lookup_code", models.CharField(max_length=24, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("public_order_code", models.CharField(max_length=32, unique=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[("account", "Account"), ("guest", "Guest")],
                        default="account",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pricing_validated", "Pricing Validated"),
                            ("payment_pending", "Payment Pending"),
                            ("paid", "Paid"),
                            ("queued", "Queued"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("picked_up", "Picked Up"),
                            ("refund_pending", "Refund Pending"),
                            ("refunded", "Refunded"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("pickup_time_requested", models.DateTimeField(blank=True, null=True)),
                ("pickup_time_estimated", models.DateTimeField(blank=True, null=True)),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("placed_at", models.DateTimeField(blank=True, null=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("preparing_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("cancel_reason", models.TextField(blank=True)),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("requested", "Requested"),
                            ("refunded", "Refunded"),
                            ("rejected", "Rejected"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("template_reference_id", models.UUIDField(blank=True, null=True)),
                ("display_name_snapshot", models.CharField(max_length=160)),
                ("size_snapshot", models.CharField(max_length=24)),
                (
                    "base_price_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("customizations_json", models.JSONField(blank=True, default=dict)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ("display_name_snapshot",),
            },
        ),
    ]
