# Generated by Django 5.1.2 on 2026-03-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="locker_code",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="order",
            name="locker_number",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
