# Generated by Django 5.1.2 on 2026-04-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_locker_code_order_locker_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="locker_code",
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
