# Generated by Django 5.1.2 on 2026-03-23 18:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('soda', 'Soda'), ('syrup', 'Syrup'), ('add_in', 'Add-In'), ('dairy', 'Dairy'), ('cups', 'Cups'), ('lids', 'Lids'), ('ice_cream', 'Ice Cream'), ('cleaning', 'Cleaning'), ('equipment', 'Equipment'), ('packaging', 'Packaging'), ('other', 'Other')], max_length=24)),
                ('unit_of_measure', models.CharField(default='unit', max_length=32)),
                ('is_perishable', models.BooleanField(default=False)),
                ('requires_frozen_storage', models.BooleanField(default=False)),
                ('default_low_stock_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sku',),
            },
        ),
        migrations.CreateModel(
            name='SupplySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommended_source_type', models.CharField(choices=[('hub', 'Hub'), ('local_supplier', 'Local Supplier'), ('local_store', 'Local Store')], max_length=24)),
                ('recommended_source_reference', models.JSONField(blank=True, default=dict)),
                ('recommended_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recommended_frequency_days', models.PositiveIntegerField()),
                ('created_by_ai', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('inactive', 'Inactive')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('store__store_code', 'inventory_item__sku'),
            },
        ),
        migrations.CreateModel(
            name='SupplyUsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_date', models.DateField()),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ('-usage_date', 'store__store_code'),
            },
        ),
        migrations.CreateModel(
            name='LocalSupplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('item_categories_json', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('service_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_suppliers', to='stores.region')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RestockAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('triggered_by', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_alerts', to='inventory.inventoryitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_alerts', to='stores.store')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StoreInventoryBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('on_hand_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_balances', to='inventory.inventoryitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='stores.store')),
            ],
            options={
                'ordering': ('store__store_code', 'inventory_item__sku'),
            },
        ),
        migrations.CreateModel(
            name='SupplierReplenishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_at', models.DateTimeField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_replenishments', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
    ]
